import type { Metadata, Viewport } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { buildThemeCss } from "@/lib/theme";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// 0226: 노치·홈바 대응 — env(safe-area-inset-*)가 실제값을 반환하려면 viewport-fit=cover 필수(기존 부재).
export const viewport: Viewport = {
  viewportFit: "cover",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        {/* 디자인 토큰 발행 — 값의 정본은 lib/theme.ts (A005 §2·§3) */}
        <style id="dotrip-theme">{buildThemeCss()}</style>
        {children}
        {/* 0241: 모바일 가로 차단 안내 — 세로 전용 앱(PWA 아님이라 CSS 오버레이). 표시 조건은 globals.css 미디어쿼리. */}
        <div className="landscape-blocker" role="alert">
          <span className="landscape-blocker__icon" aria-hidden>📱</span>
          <p className="landscape-blocker__title">세로로 돌려주세요</p>
          <p className="landscape-blocker__sub">이 화면은 세로 모드에 최적화되어 있어요</p>
        </div>
      </body>
    </html>
  );
}
