import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { buildThemeCss } from "@/lib/theme";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        {/* 디자인 토큰 발행 — 값의 정본은 lib/theme.ts (A005 §2·§3) */}
        <style id="dotrip-theme">{buildThemeCss()}</style>
        {children}
      </body>
    </html>
  );
}
